{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lldk.secretName" . }}
  labels:
    {{- include "lldk.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.bootstrapAdminKey }}
  bootstrapAdminKey: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.metricsToken }}
  metricsToken: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.openaiCompatApiKey }}
  openaiCompatApiKey: {{ . | quote }}
  {{- end }}
{{- end }}
